layout_spectrum: 0.4183446611277759
typography_spectrum: 0.6054945895448327
color:
  brandStrength: 0.9917666281107813
  lightness: 0.6039553275331855
  saturation: 0.36281893751583993
  rhythmicContrast: 0.5985045828856528
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
name: Nebuchadnezzar
navigation:
  - name: My YouTube Channel
    url: 'https://www.youtube.com/channel/UCOleqp98ohqeU5uop6Ez2Qw'
    type: external
title: Sherpain
description: All things I make.
