layout_spectrum: 0.6981122682336718
typography_spectrum: 0.267308788606897
color:
  brandStrength: 0.5355947290081531
  lightness: 0.6439713449217379
  saturation: 0.8664882911834866
  rhythmicContrast: 0.9124570237472653
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
name: Nebuchadnezzar
navigation:
  - name: My YouTube Channel
    url: 'https://www.youtube.com/channel/UCOleqp98ohqeU5uop6Ez2Qw'
    type: external
title: Sherpain
description: The Beginning
