typography_spectrum: 0.09591437131166458
color:
  brandStrength: 0.3136166180483997
  lightness: 0.4848497419152409
  saturation: 0.8961333518382162
  rhythmicContrast: 0.14387531112879515
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.7624656073749065
name: Nebuchadnezzar
navigation:
  - name: My YouTube Channel
    url: 'https://www.youtube.com/channel/UCOleqp98ohqeU5uop6Ez2Qw'
    type: external
title: Sherpain
description: All things I make.
